manifest = "274928156a3ad767ae4d064051e2f25651683964a88561a7452db6930e02da47"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.43.0" ]
revision = "b372c24ab8b55df3a336bc4f0b200014369d6d96"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.43.0" ]
revision = "77ca029d6666ae6c9d11b7fae0f2c6424020fead"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.43.0" ]
revision = "71e2798b88ab175cc2c904a8d1863b69a02f9a09"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.43.0" ]
revision = "a6ae91770d6f17fb5aa6fd402c4353d4ef355f71"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.43.0" ]
revision = "d19e409d08aa20728074f8eda6d26546b3046789"
