manifest = "7f897d7404bd62555f180e1f51bcc221d8c1004ad1f98b5de72a2911ab2b4b13"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.62.0" ]
revision = "484f0f9359c0896a0ea9ae1f471c4586b2bb1591"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.62.0" ]
revision = "8e0bd7d950d98d4dd62a61b31ad6cd90e0ab3fd9"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.62.0" ]
revision = "aabf1b51ad20471ec869ae8db30d4f8da170e6a2"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.62.0" ]
revision = "61e5cbe0edab2492008d5e8a7966ac70aada9dfa"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.62.0" ]
revision = "aed0a64c4a565f629c3ae67e1ab0657ff6934db7"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.62.0" ]
revision = "2e64310825036f60972e8f91189aa4b36647a47d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.62.0" ]
revision = "3ddcf9ceb2f5b7894128928e2bc8bb03ddca16b7"
